name: Performance Test

on:
  workflow_dispatch:   # manual trigger
  push:
    branches: [main]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  jmeter-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install JMeter
        run: |
          sudo apt-get update
          sudo apt-get install -y jmeter

      - name: Run JMeter Test
        run: |
          jmeter -n -t sample.jmx -l results.jtl \
          -Jxstream.allow=org.apache.jmeter.save.ScriptWrapper

      - name: Upload Results
        uses: actions/upload-artifact@v6
        with:
          name: jmeter-results
          path: results.jtl
