name: Performance Test

on:
  workflow_dispatch:   # manual trigger
  push:
    branches: [main]

jobs:
  jmeter-test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run JMeter in Docker
        run: |
          docker run `
            -v "${{ github.workspace }}:/test" `
            justb4/jmeter `
            -n `
            -t /test/sample.jmx `
            -l /test/results.jtl `
            -j /test/jmeter.log

      - name: Print logs
        run: cat jmeter.log

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: |
            results.jtl
            jmeter.log
